[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node ./dist/server/entry.mjs"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.envs]
PORT = "3000"